"""
Photo Directory Subsystem Comparator
====================================

This script compares two tab-separated values (TSV) report spreadsheets 
generated by photo_dir_reporter.py:
1. Primary File: The new batch list of files you want to check.
2. Repository File: The master archival list containing all known files.

It cross-references files by matching their names and sizes. It then outputs a 
new spreadsheet marking each item as either 'duplicate' or 'unique' compared 
to your master repository archive.

================================================================================
"""

import csv
import os
import tkinter as tk
from tkinter import filedialog, messagebox
import photo_dir_utils as utils

def extract_year(date_str):
    """
    Extracts the 4-digit calendar year from a standard date string.

    Args:
        date_str (str): A date string formatted as 'mm/dd/yyyy'.

    Returns:
        str: The 4-digit year string if valid, or 'Unknown' if the format 
             cannot be processed.
    """
    if not date_str:
        return ""
    parts = date_str.strip().split('/')
    if len(parts) == 3 and len(parts[2]) == 4:
        return parts[2]
    return "Unknown"

def load_repository_signature(repo_path):
    """
    Reads the master repository report and builds a fast lookup reference table.

    Normalizes file names by stripping standard duplication flags (like ' copy') 
    before storing them to ensure accurate comparison matching.

    Args:
        repo_path (str): The absolute path to the master repository TSV file.

    Returns:
        dict: A reference tracking table where each key is a tracking match 
              composed of (normalized_name, file_size) and the value is a 
              dictionary with the original filename and directory path. 
              Returns None if an error occurs.
    """
    repo_map = {}
    print(f"Loading Repository: {os.path.basename(repo_path)}...")
    
    try:
        with open(repo_path, mode='r', newline='', encoding='utf-8') as f:
            reader = csv.DictReader(f, delimiter='\t')
            # Clean accidental whitespace from spreadsheet column headers
            reader.fieldnames = [h.strip() for h in reader.fieldnames]
            
            for row in reader:
                fname = row.get('Filename', '').strip()
                fsize = row.get('Size (KB)', '0').strip()
                
                # Strip export duplication tags via the shared pipeline utility
                norm_name = utils.normalize_filename(fname)
                
                # Combine name and size to form a unique match key
                key = (norm_name, fsize)
                
                # If duplicates exist within the master repository itself, 
                # keep the first one found as our tracking reference point.
                if key not in repo_map:
                    repo_map[key] = {
                        'filename': fname,
                        'path': row.get('Directory path', '')
                    }
        print(f"Repository loaded. {len(repo_map)} unique file matches found.")
        return repo_map

    except Exception as e:
        messagebox.showerror("Error", f"Failed to read repository file:\n{e}")
        return None

def process_comparison():
    """
    Launches interactive windows to select report spreadsheets and runs 
    the duplicate comparison loop.
    """
    # Initialize Tkinter and hide the main layout window
    root = tk.Tk()
    root.withdraw()

    # Automatically open the selection window at the most recently accessed directory
    start_dir = utils.get_start_dir()

    # 1. Select Primary File
    print("Select the PRIMARY file (the list to check)...")
    primary_path = filedialog.askopenfilename(
        title="Select PRIMARY Input File (The list to check)",
        initialdir=start_dir,
        filetypes=[("TSV Files", "*.tsv")]
    )
    if not primary_path:
        print("Operation cancelled.")
        return

    # 2. Select Repository File
    print("Select the REPOSITORY file (the master list)...")
    repo_path = filedialog.askopenfilename(
        title="Select REPOSITORY File (The master list)",
        initialdir=os.path.dirname(primary_path), # Start where the primary file is
        filetypes=[("TSV Files", "*.tsv")]
    )
    if not repo_path:
        print("Operation cancelled.")
        return

    # Save this location as the most recently accessed directory
    utils.save_start_dir(os.path.dirname(primary_path))

    # 3. Load Master Repository Reference Data
    repo_map = load_repository_signature(repo_path)
    if not repo_map:
        return

    # 4. Generate Output Status Filename
    # Changes a source "_file_report.tsv" suffix into "_file_status_report.tsv"
    base_dir = os.path.dirname(primary_path)
    input_filename = os.path.basename(primary_path)
    
    if "_file_report.tsv" in input_filename:
        output_filename = input_filename.replace("_file_report.tsv", "_file_status_report.tsv")
    else:
        # Fallback naming rule if the primary file does not match expectations
        base, ext = os.path.splitext(input_filename)
        output_filename = f"{base}_status_report{ext}"
    
    output_path = os.path.join(base_dir, output_filename)

    # 5. Read Primary File Rows and Write Match Status Results
    print(f"Comparing files and writing to: {output_filename}")
    
    try:
        with open(primary_path, mode='r', newline='', encoding='utf-8') as f_in, \
             open(output_path, mode='w', newline='', encoding='utf-8') as f_out:
            
            reader = csv.DictReader(f_in, delimiter='\t')
            reader.fieldnames = [h.strip() for h in reader.fieldnames]

            # Define output report structure layout columns
            fieldnames = [
                'filename', 
                'file path', 
                'year', 
                'status', 
                'dup filename', 
                'dup file path'
            ]
            writer = csv.DictWriter(f_out, fieldnames=fieldnames, delimiter='\t')
            writer.writeheader()

            processed_count = 0
            dup_count = 0

            for row in reader:
                src_fname = row.get('Filename', '').strip()
                src_path = row.get('Directory path', '').strip()
                src_size = row.get('Size (KB)', '0').strip()
                src_date = row.get('Date (mm/dd/yyyy)', '')

                # Standardize incoming names to make matching completely accurate
                norm_name = utils.normalize_filename(src_fname)
                key = (norm_name, src_size)

                # Cross-reference the key against our master tracking database map
                match = repo_map.get(key)
                
                # Prepare row values based on whether a match was found
                if match:
                    status = 'duplicate'
                    dup_fname = match['filename']
                    dup_path = match['path']
                    dup_count += 1
                else:
                    status = 'unique'
                    dup_fname = ''
                    dup_path = ''

                year_val = extract_year(src_date)

                # Write final processed tracking row out to disk
                writer.writerow({
                    'filename': src_fname,
                    'file path': src_path,
                    'year': year_val,
                    'status': status,
                    'dup filename': dup_fname,
                    'dup file path': dup_path
                })
                processed_count += 1

        # Build and display terminal and pop-up workspace metrics summaries
        msg = (f"Report Complete.\n\n"
               f"Total Processed: {processed_count}\n"
               f"Duplicates Found: {dup_count}\n"
               f"Unique Files: {processed_count - dup_count}\n\n"
               f"Saved to:\n{output_filename}")
        
        print(msg)
        messagebox.showinfo("Comparison Complete", msg)

    except Exception as e:
        print(f"Error during processing: {e}")
        messagebox.showerror("Processing Error", str(e))

if __name__ == "__main__":
    process_comparison()
