"""
Photo Directory Subsystem Duplicate Matrix Analyzer
===================================================

This script analyzes a single file report generated by photo_dir_reporter.py. 
It identifies internal duplicate files by matching identical names and sizes.

Instead of a flat list, it builds an interactive matrix spreadsheet. The 
columns represent your subdirectories, and the rows display duplicate files. 
The intersecting cells show the modification dates of those duplicate copies. 

This matrix makes it easy to visualize precisely how redundant file groups 
are scattered across different backup folders or staging drives.

================================================================================
"""

import csv
import os
import tkinter as tk
from tkinter import filedialog, messagebox, StringVar, Radiobutton, Label, Entry, Button
from collections import Counter, defaultdict

def normalize_filename(filename):
    """
    Removes the trailing ' copy' suffix from a filename stem.

    Args:
        filename (str): The raw file name to normalize.

    Returns:
        str: The modified filename string without duplicate tags.
    """
    base, ext = os.path.splitext(filename)
    normalized_base = base.replace(' copy', '')
    return normalized_base + ext

def get_group_name(files_in_group):
    """
    Selects the shortest original filename from a group of duplicates 
    to serve as the primary display label for the spreadsheet row.

    Args:
        files_in_group (list): A list of original filename strings.

    Returns:
        str: The shortest filename in the collection.
    """
    files_in_group.sort(key=lambda x: (len(x), x))
    return files_in_group[0]

def analyze_directory_sets(all_duplicate_groups):
    """
    Groups related directories together by analyzing which folders share 
    the highest volume of matching duplicate files.

    Args:
        all_duplicate_groups (list): A list of lists, where each sub-list 
                                     contains rows of matching duplicate items.

    Returns:
        dict: A mapping of directory paths to a tracking tuple containing 
              a assigned Set Label and the total match count for that folder.
    """
    dir_counts = Counter()
    adjacency = defaultdict(set)

    # Count how often duplicates appear in each folder
    for group in all_duplicate_groups:
        for row in group:
            d = row.get('Directory path', '')
            dir_counts[d] += 1

        # Track connections between directories that share duplicate items
        dirs_in_group = list(set(row.get('Directory path', '') for row in group))
        for i in range(len(dirs_in_group)):
            for j in range(i + 1, len(dirs_in_group)):
                d1 = dirs_in_group[i]
                d2 = dirs_in_group[j]
                adjacency[d1].add(d2)
                adjacency[d2].add(d1)

    # Sort folders so that the ones containing the most duplicates are handled first
    remaining_dirs = sorted(list(dir_counts.keys()), key=lambda x: dir_counts[x], reverse=True)
    dir_to_set = {}
    set_index = 1

    # Cluster connected folders into shared logical groups
    while remaining_dirs:
        pivot = remaining_dirs[0]
        current_set_name = f"Set {set_index}"
        
        # Assign the pivot directory to the current folder group
        dir_to_set[pivot] = (current_set_name, dir_counts[pivot])
        remaining_dirs.remove(pivot)
        
        # Check folders connected to the pivot and group them together 
        # if they have not been claimed by a prior set.
        connected = adjacency[pivot]
        to_remove = []
        for d in remaining_dirs:
            if d in connected:
                dir_to_set[d] = (current_set_name, dir_counts[d])
                to_remove.append(d)
        for d in to_remove:
            remaining_dirs.remove(d)
            
        set_index += 1

    return dir_to_set

class DuplicateReportApp:
    """
    Interactive Graphic User Interface configuration window for choosing 
    the master spreadsheet report, filter restrictions, and output targets.
    """
    def __init__(self, root):
        self.root = root
        self.root.title("Duplicate Matrix Configuration Panel")
        
        self.input_file = ""
        self.filter_mode = StringVar(value="full")
        self.subset_path = StringVar()

        # Input File Selection Widgets
        Label(root, text="Select Input Report File:").grid(row=0, column=0, sticky='w', padx=10, pady=5)
        self.file_label = Label(root, text="No file selected", fg="red", width=50, anchor='w')
        self.file_label.grid(row=0, column=1, padx=10, pady=5)
        Button(root, text="Browse...", command=self.browse_file).grid(row=0, column=2, padx=10, pady=5)

        # Analysis Filter Options
        Label(root, text="Analysis Filter Mode:").grid(row=1, column=0, sticky='w', padx=10, pady=5)
        
        Radiobutton(root, text="Full Matrix (All duplicates across folders)", 
                    variable=self.filter_mode, value="full", command=self.toggle_entry).grid(row=1, column=1, sticky='w')
        Radiobutton(root, text="Subset Match (At least one copy exists in specified folder)", 
                    variable=self.filter_mode, value="sub", command=self.toggle_entry).grid(row=2, column=1, sticky='w')
        Radiobutton(root, text="Isolated Match (Only matches entirely inside specified folder)", 
                    variable=self.filter_mode, value="none", command=self.toggle_entry).grid(row=3, column=1, sticky='w')

        # Folder Path Filter Target String Field
        Label(root, text="Target Filter Folder Substring:").grid(row=4, column=0, sticky='w', padx=10, pady=5)
        self.entry_path = Entry(root, textvariable=self.subset_path, width=50, state='disabled')
        self.entry_path.grid(row=4, column=1, padx=10, pady=5)

        # Execution Controls
        Button(root, text="Generate Matrix Report", command=self.run_analysis, bg="green", fg="white").grid(row=5, column=1, pady=15)

    def browse_file(self):
        """Opens a file selector box to choose the base report sheet."""
        # Note: You can optionally swap this line to look up the shared 
        # utils configuration folder when integrating with the broader suite.
        path = filedialog.askopenfilename(filetypes=[("TSV Files", "*.tsv")])
        if path:
            self.input_file = path
            self.file_label.config(text=os.path.basename(path), fg="green")

    def toggle_entry(self):
        """Enables or disables the text entry field based on the radio option selection."""
        if self.filter_mode.get() in ["sub", "none"]:
            self.entry_path.config(state='normal')
        else:
            self.entry_path.config(state='disabled')

    def run_analysis(self):
        """Validates option inputs and kicks off the background matrix generation."""
        if not self.input_file:
            messagebox.showerror("Error", "Please select an input TSV file report before proceeding.")
            return
        
        mode = self.filter_mode.get()
        target_str = self.subset_path.get().strip()

        if mode in ["sub", "none"] and not target_str:
            messagebox.showerror("Error", "Filter modes require a target folder text string to evaluate.")
            return

        self.root.destroy()
        generate_report(self.input_file, mode, target_str)

def generate_report(input_path, mode, target_string):
    """
    Parses the index spreadsheet, determines matching groups, applies 
    user-configured filtering constraints, and exports the final grid.
    """
    print(f"Reading file report data: {os.path.basename(input_path)}...")
    
    # Tracking logs for building file statistics
    file_groups = defaultdict(list)
    total_files_in_dir = Counter()
    dup_counts_in_subset = Counter()

    try:
        with open(input_path, mode='r', newline='', encoding='utf-8') as infile:
            reader = csv.DictReader(infile, delimiter='\t')
            reader.fieldnames = [h.strip() for h in reader.fieldnames]

            for row in reader:
                fname = row.get('Filename', '').strip()
                fsize = row.get('Size (KB)', '0').strip()
                dpath = row.get('Directory path', '').strip()

                if not fname:
                    continue

                total_files_in_dir[dpath] += 1
                
                # Standardize names using utility logic before grouping
                norm_name = normalize_filename(fname)
                group_key = (norm_name, fsize)
                file_groups[group_key].append(row)

        # Filter the dictionary down to only keep groups that have actual duplicates
        raw_duplicate_groups = [g for g in file_groups.values() if len(g) > 1]
        
        # Analyze connections to divide directories into logical sets
        dir_to_set_map = analyze_directory_sets(raw_duplicate_groups)

        filtered_groups = []
        for group in raw_duplicate_groups:
            # Extract lists of directories present in this specific duplicate group
            dirs_in_group = [row.get('Directory path', '') for row in group]

            # Condition Check: Is the folder substring present anywhere in the group?
            has_target_substring = any(target_string in d for d in dirs_in_group)
            
            # Condition Check: Are ALL copies trapped inside the target folder area?
            all_inside_target = all(target_string in d for d in dirs_in_group)

            if mode == "full":
                filtered_groups.append(group)
            elif mode == "sub" and has_target_substring:
                filtered_groups.append(group)
            elif mode == "none" and all_inside_target:
                filtered_groups.append(group)

        if not filtered_groups:
            messagebox.showinfo("Complete", "No duplicate files matched your filter settings.")
            return

        # Dynamically build and sort the list of column headers
        all_unique_dirs = set()
        for group in filtered_groups:
            for row in group:
                all_unique_dirs.add(row.get('Directory path', ''))

        # Sort columns based on their assigned logical set groupings
        dir_columns = sorted(list(all_unique_dirs), key=lambda x: (dir_to_set_map.get(x, ("", 0))[0], x))

        # Build output spreadsheet filename target
        base_dir = os.path.dirname(input_path)
        input_filename = os.path.basename(input_path)
        suffix_map = {"full": "_full_matrix.tsv", "sub": "_subset_matrix.tsv", "none": "_isolated_matrix.tsv"}
        
        output_filename = input_filename.replace("_file_report.tsv", suffix_map[mode])
        if output_filename == input_filename:
            base, _ = os.path.splitext(input_filename)
            output_filename = f"{base}{suffix_map[mode]}"
        
        output_path = os.path.join(base_dir, output_filename)

        # Re-verify and count duplicate file numbers for summary values
        for group in filtered_groups:
            for row in group:
                dpath = row.get('Directory path', '')
                dup_counts_in_subset[dpath] += 1

        # Transform and sort row items for matrix writing
        matrix_rows = []
        for group in filtered_groups:
            filenames_in_group = [row.get('Filename', '') for row in group]
            row_label_name = get_group_name(filenames_in_group)
            
            date_mappings = {}
            for row in group:
                dpath = row.get('Directory path', '')
                mod_date = row.get('Date (mm/dd/yyyy)', '')
                date_mappings[dpath] = mod_date

            matrix_rows.append({
                'name': row_label_name,
                'dates': date_mappings,
                'total_count': len(group)
            })

        matrix_rows.sort(key=lambda x: x['name'])

        # Write final matrix spreadsheet report out to disk
        print(f"Writing matrix spreadsheet: {output_filename}...")
        with open(output_path, mode='w', newline='', encoding='utf-8') as outfile:
            writer = csv.writer(outfile, delimiter='\t')
            
            headers = ["Duplicate Filename Group"] + dir_columns + ["Total Copies Found"]
            writer.writerow(headers)
            
            for item in matrix_rows:
                row_output = [item['name']]
                for d_col in dir_columns:
                    row_output.append(item['dates'].get(d_col, ""))
                row_output.append(item['total_count'])
                writer.writerow(row_output)
            
            # Append mathematical summaries to base of grid columns
            summary_dups = ["# of duplicate files in directory"]
            for d_col in dir_columns:
                summary_dups.append(dup_counts_in_subset[d_col])
            summary_dups.append("")
            writer.writerow(summary_dups)
            
            summary_totals = ["Total # of files in directory"]
            for d_col in dir_columns:
                summary_totals.append(total_files_in_dir[d_col])
            summary_totals.append("")
            writer.writerow(summary_totals)

        messagebox.showinfo("Success", f"Matrix Report Complete:\n{output_filename}")
        print("Processing run complete.")

    except Exception as e:
        print(f"Execution Error: {e}")
        messagebox.showerror("Error", str(e))

if __name__ == "__main__":
    # Initialize interactive dialog panel
    main_window = tk.Tk()
    app = DuplicateReportApp(main_window)
    main_window.mainloop()

    
